#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#   - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse off

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus off

# render all unfocused windows with 90% opacity
#yabai -m config window_opacity on
#yabai -m config window_opacity_duration 0.0
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.9

# render iTerm2 with 95% opacity
#yabai -m rule --add app="iTerm2" opacity=0.95
# render vscode with 95% opacity
#yabai -m rule --add app="Code" opacity=0.95

# default settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

# useful command:
#
#   $ yabai -m query --windows | jq ".[] | { App: .app, Title: .title }"
#
# float system preferences
yabai -m rule --add app="^Android File Transfer$" manage=off
yabai -m rule --add app="^Android Studio$" title="^Generate Signed Bundle or APK$" manage=off
yabai -m rule --add app="^Android Studio$" title="^New Key Store$" manage=off
yabai -m rule --add app="^Android Studio$" title="^Preferences$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add app="^Parallels Desktop$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Simulator.*$" manage=off
yabai -m rule --add app="^Software Update$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="^Xcode$" title="^Archives$" manage=off

# make sure always has 9 workspaces
# for yabai v3:
#CURRENT_WORKSPACES_COUNT=$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0)) | length')
# for yabai v4:
CURRENT_WORKSPACES_COUNT=$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false)) | length')

if [[ $CURRENT_WORKSPACES_COUNT -lt 9 ]]; then
  for _ in $(seq 1 $(( 9 - $CURRENT_WORKSPACES_COUNT ))); do
    yabai -m space --create
  done
elif [[ $CURRENT_WORKSPACES_COUNT -gt 9 ]]; then
  for _ in $(seq 1 $(( $CURRENT_WORKSPACES_COUNT - 9 ))); do
    yabai -m space --destroy
  done
fi

# add some padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:32:0
